In [1]:
import numpy as np

In [10]:
print(l)
import numpy as np

[2, 3, 4, 5, 6]


In [25]:
import numpy as np
l=list(map(int,input("").split()))
l=np.array(l,dtype='f')
print(l[::-1])

2 3 4 5 6 7 8
[8. 7. 6. 5. 4. 3. 2.]


In [26]:
import numpy as np


l=list(map(int,input("").split()))


l=np.array(l).reshape(3,3)
print(l)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
l=list(map(int,input("").split()))
print(np.zeros((l), dtype = int))
print(np.ones((l), dtype = int))


2 2 2
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [35]:
arr

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
n,m = map(int,input("").split())

l=[]
for i in range(n):
    l.append(list(map(int,input("").split())))
l=np.min(np.max(np.array(l),axis=1), axis=0)

In [14]:
l=np.max(np.array(l),axis=1)
l

AxisError: axis 1 is out of bounds for array of dimension 1

In [3]:
m=[l.append(list(map(int,input("").split()))) for i in range(n)]

2 4
4 2


In [4]:
m

[None, None]

In [12]:

A+B
print(A-B)
print(A*B)
print(A%B)
print(A**B)

[1 1 1]
[ 2  6 12]
[0 1 1]
[ 2  9 64]


[3 5 7]


In [13]:
np.divide()

(array([2, 1, 1], dtype=int32), array([0, 1, 1], dtype=int32))

In [17]:
n,m = map(int,input("").split())
l=[]
for i in range(n):
    l.append(list(map(int,input("").split())))
    
l=my_array = np.array([ [1, 2], [3, 4] ])
print(np.prod(np.sum(l,axis=0)))

24


In [22]:
l=my_array = np.array([ [1, 2], [3, 4] ])

print(np.mean(l,axis=1))
print(np.var(l,axis=0))
print(round(np.std(l),11))

[1.5 3.5]
[1. 1.]
1.11803398875


In [25]:
A = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])


In [28]:
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [ ]:
    [1. 2. 3. 4. 5. 6. 7. 8. 9.]

    [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

    [ 1.  2.  3.  4.  6.  7.  8.  9. 10.]

    [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

    [  2.   3.   4.   5.   6.   7.   8.   9.  10.]

    [  1.   2.   3.   4.   6.   7.   8.   9.  10.]
    