In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
a

0    26
1    38
2    35
3    20
4    35
5    21
6    22
7    20
8    37
9    32
dtype: int32

In [56]:
a = pd.Series(np.random.randint(20,40,10))

In [46]:
a

0    30
1    35
2    30
3    27
4    30
5    21
6    34
7    28
8    26
9    38
dtype: int32

In [47]:
top = []
for i in range(5):
    top.append(a.min())
    a = a.drop(index = a.argmin())
    print(a)

0    30
1    35
2    30
3    27
4    30
6    34
7    28
8    26
9    38
dtype: int32
0    30
1    35
2    30
3    27
4    30
6    34
8    26
9    38
dtype: int32
0    30
1    35
2    30
3    27
4    30
8    26
9    38
dtype: int32


KeyError: '[5] not found in axis'

In [48]:
top

[21, 26, 26, 26]

In [37]:
a

1    32
2    25
7    22
8    35
9    23
dtype: int32

In [38]:
top

[22, 22, 22, 22, 22]

In [10]:
aa.drop(index=3)

0    39
1    32
4    25
5    35
6    36
7    30
8    35
9    39
dtype: int32

In [23]:
aa = aa.drop(index=5)

In [25]:
aa.argmin()

1

In [26]:
aa

0    39
1    25
2    26
3    35
6    26
7    37
8    31
9    38
dtype: int32

In [28]:
aa.min()

25

In [54]:
a = pd.Series(np.random.randint(20,40,10))
mini = []
for i in range(5):
    print(a)
    i = a.argmin()
    mini.append(a[i])
    a = a.drop(index=i)

0    22
1    32
2    35
3    27
4    32
5    31
6    35
7    34
8    30
9    25
dtype: int32
1    32
2    35
3    27
4    32
5    31
6    35
7    34
8    30
9    25
dtype: int32
1    32
2    35
3    27
4    32
5    31
6    35
7    34
9    25
dtype: int32
1    32
2    35
3    27
4    32
5    31
6    35
9    25
dtype: int32
1    32
2    35
3    27
4    32
5    31
9    25
dtype: int32


In [55]:
mini

[22, 30, 34, 35, 31]

In [68]:
a.argmin()

2

In [66]:
a = a.drop(3)

In [69]:
a[6]

21

In [70]:
a[2]

KeyError: 2

In [71]:
a = pd.Series(np.random.randint(20,40,10))

In [72]:
a

0    39
1    24
2    27
3    24
4    26
5    33
6    34
7    36
8    27
9    38
dtype: int32

In [73]:
a.drop(3)

0    39
1    24
2    27
4    26
5    33
6    34
7    36
8    27
9    38
dtype: int32

In [74]:
a.drop(2)

0    39
1    24
3    24
4    26
5    33
6    34
7    36
8    27
9    38
dtype: int32

In [75]:
a.drop([4, 5])

0    39
1    24
2    27
3    24
6    34
7    36
8    27
9    38
dtype: int32

In [76]:
ser = pd.Series(np.random.randint(1, 10, 10), index=list("ABCDEFGHIJ"))

In [78]:
ser.drop(2)

KeyError: '[2] not found in axis'

In [80]:
ser[2]

3

In [82]:
ser.index

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object')

In [83]:
a.index

RangeIndex(start=0, stop=10, step=1)

In [85]:
ser.drop('B')

A    2
C    3
D    1
E    4
F    3
G    7
H    9
I    2
J    3
dtype: int32

In [86]:
ser.drop('A')

B    9
C    3
D    1
E    4
F    3
G    7
H    9
I    2
J    3
dtype: int32

In [87]:
ser.drop(['E', 'G'])

A    2
B    9
C    3
D    1
F    3
H    9
I    2
J    3
dtype: int32

In [88]:
ser.drop(index=2)

KeyError: '[2] not found in axis'

In [90]:
a

0    39
1    24
2    27
3    24
4    26
5    33
6    34
7    36
8    27
9    38
dtype: int32

In [91]:
a.argmin()

1

In [93]:
a = a.drop(1)

In [94]:
a

0    39
2    27
3    24
4    26
5    33
6    34
7    36
8    27
9    38
dtype: int32

In [95]:
a.argmin()

2

In [96]:
a.drop(2)

0    39
3    24
4    26
5    33
6    34
7    36
8    27
9    38
dtype: int32

In [107]:
a = pd.Series(np.random.randint(20,40,10))
mini = []
for i in range(5):
    i = a.argmin()
    mini.append(a[i])
    a = a.drop(index=i)
    a.index = range(0, len(a))

In [108]:
mini

[20, 20, 21, 23, 26]

In [109]:
a

0    37
1    33
2    31
3    38
4    35
dtype: int32

In [110]:
ser

A    2
B    9
C    3
D    1
E    4
F    3
G    7
H    9
I    2
J    3
dtype: int32

In [111]:
ser.argmin()

3

In [112]:
ser.argmax()

1

In [115]:
ser[ser.argsort()]

D    1
A    2
I    2
C    3
F    3
J    3
E    4
G    7
B    9
H    9
dtype: int32

In [116]:
ser.argsort()

A    3
B    0
C    8
D    2
E    5
F    9
G    4
H    6
I    1
J    7
dtype: int64

In [118]:
ser.count()  # null value is not included 

10

In [119]:
ser.value_counts()

3    3
2    2
9    2
1    1
4    1
7    1
dtype: int64

In [122]:
dose1 = pd.Series(np.random.choice(['Yes', 'No'], 20))

In [124]:
dose1.value_counts()

Yes    11
No      9
dtype: int64

In [125]:
np.nan

nan

In [133]:
arr = np.random.randn(20)

In [190]:
arr[[2, 3, 7, 9, 12]] = np.nan

In [136]:
arr

array([ 1.27494963, -1.07940786,         nan,         nan, -0.13481033,
       -0.17840372,  2.45462739,         nan,  0.89466587,         nan,
       -0.41003417,  0.50709515,         nan,  2.5680835 , -2.03615033,
        0.12677774,  0.5695417 , -0.96293044, -0.46603733, -2.17000311])

In [138]:
np.isnan(arr).sum()

5

In [140]:
arr[np.isnan(arr)]

array([nan, nan, nan, nan, nan])

    We have 2 options to handle null values 
    
        1. to remove permanently
        2. to replace

In [144]:
np.nanargmax(arr)

13

In [147]:
arr == np.nan

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [157]:
arr == 1.27494963

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [163]:
np.round(arr) == 1

array([ True, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False,  True, False,
       False, False])

In [156]:
a == 37

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [164]:
np.round(arr) == np.nan

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [166]:
np.isnan(arr)

array([False, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False, False])

In [169]:
arr.mean()
# nan + value = nan

nan

In [172]:
arr.mean()

nan

In [177]:
np.isnan(arr)

array([False, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False, False])

In [181]:
m = arr[~ np.isnan(arr)].mean()  # found the values which are not  none

In [182]:
arr

array([ 1.27494963, -1.07940786,         nan,         nan, -0.13481033,
       -0.17840372,  2.45462739,         nan,  0.89466587,         nan,
       -0.41003417,  0.50709515,         nan,  2.5680835 , -2.03615033,
        0.12677774,  0.5695417 , -0.96293044, -0.46603733, -2.17000311])

In [183]:
### now replacing the none values with mean
### benefit of replacing with mean is the overall mean remains same 

In [186]:
m

0.06386424689541652

In [184]:
arr[np.isnan(arr)]= m

In [185]:
arr

array([ 1.27494963, -1.07940786,  0.06386425,  0.06386425, -0.13481033,
       -0.17840372,  2.45462739,  0.06386425,  0.89466587,  0.06386425,
       -0.41003417,  0.50709515,  0.06386425,  2.5680835 , -2.03615033,
        0.12677774,  0.5695417 , -0.96293044, -0.46603733, -2.17000311])

In [187]:
arr.dtype

dtype('float64')

In [188]:
arr.mean()

0.06386424689541652

In [189]:
m == arr.mean()

True

In [192]:
arr

array([ 1.27494963, -1.07940786,         nan,         nan, -0.13481033,
       -0.17840372,  2.45462739,         nan,  0.89466587,         nan,
       -0.41003417,  0.50709515,         nan,  2.5680835 , -2.03615033,
        0.12677774,  0.5695417 , -0.96293044, -0.46603733, -2.17000311])

In [195]:
np.delete(arr, np.where(np.isnan(arr)))  # remove the none values 

array([ 1.27494963, -1.07940786, -0.13481033, -0.17840372,  2.45462739,
        0.89466587, -0.41003417,  0.50709515,  2.5680835 , -2.03615033,
        0.12677774,  0.5695417 , -0.96293044, -0.46603733, -2.17000311])

In [197]:
ser[['B', 'D', 'F', 'G']] = np.nan

In [198]:
ser

A    2.0
B    NaN
C    3.0
D    NaN
E    4.0
F    NaN
G    NaN
H    9.0
I    2.0
J    3.0
dtype: float64

In [199]:
ser == np.nan

A    False
B    False
C    False
D    False
E    False
F    False
G    False
H    False
I    False
J    False
dtype: bool

In [201]:
ser.value_counts()

3.0    2
2.0    2
4.0    1
9.0    1
dtype: int64

In [202]:
ser.count()

6

In [203]:
ser

A    2.0
B    NaN
C    3.0
D    NaN
E    4.0
F    NaN
G    NaN
H    9.0
I    2.0
J    3.0
dtype: float64

In [206]:
ser[ser.isna()]

B   NaN
D   NaN
F   NaN
G   NaN
dtype: float64

In [209]:
ser.mean()

3.8333333333333335

In [210]:
ser.mean(skipna=False)  

nan

In [211]:
ser.mean(skipna=True)

3.8333333333333335

In [212]:
ser.mean()

3.8333333333333335

In [214]:
ser[ser.isna()] = ser.mean()

In [215]:
ser

A    2.000000
B    3.833333
C    3.000000
D    3.833333
E    4.000000
F    3.833333
G    3.833333
H    9.000000
I    2.000000
J    3.000000
dtype: float64

In [216]:
ser.mean()

3.833333333333333

In [217]:
ser[['B', 'D', 'F', 'G']] = np.nan

In [218]:
ser.fillna(ser.mean())
# fill my none values with series mean 

A    2.000000
B    3.833333
C    3.000000
D    3.833333
E    4.000000
F    3.833333
G    3.833333
H    9.000000
I    2.000000
J    3.000000
dtype: float64

In [220]:
ser.fillna('hi')

A    2.0
B     hi
C    3.0
D     hi
E    4.0
F     hi
G     hi
H    9.0
I    2.0
J    3.0
dtype: object

In [221]:
ser

A    2.0
B    NaN
C    3.0
D    NaN
E    4.0
F    NaN
G    NaN
H    9.0
I    2.0
J    3.0
dtype: float64

In [224]:
ser[ser.isna()].index

Index(['B', 'D', 'F', 'G'], dtype='object')

In [225]:
ser.drop(ser[ser.isna()].index)  # remove

A    2.0
C    3.0
E    4.0
H    9.0
I    2.0
J    3.0
dtype: float64

In [227]:
ser.dropna()

A    2.0
C    3.0
E    4.0
H    9.0
I    2.0
J    3.0
dtype: float64

In [231]:
ser = ser.fillna(2.5)

In [234]:
ser < 2

A    False
B    False
C    False
D    False
E    False
F    False
G    False
H    False
I    False
J    False
dtype: bool

In [236]:
ser[ser > 5]

H    9.0
dtype: float64

In [238]:
ser[ser%2 == 0]

A    2.0
E    4.0
I    2.0
dtype: float64

In [241]:
ser[(ser%2==0) & (ser>2)]

E    4.0
dtype: float64

In [242]:
ser[(ser%2==0) | (ser>2)]

A    2.0
B    2.5
C    3.0
D    2.5
E    4.0
F    2.5
G    2.5
H    9.0
I    2.0
J    3.0
dtype: float64

### DataFrame

    Collection of series or 2D data 
    
        It consists of rows and columns

In [244]:
np.random.randint(1, 10, (5, 5))

array([[2, 9, 4, 6, 3],
       [5, 1, 7, 2, 4],
       [2, 9, 4, 6, 3],
       [5, 1, 2, 8, 1],
       [4, 9, 3, 5, 3]])

In [245]:
pd.DataFrame(np.random.randint(1, 10, (5, 5)))

0  1  2  3  4
0  8  4  4  4  6
1  9  8  2  5  6
2  9  7  2  1  3
3  1  9  2  8  8
4  7  9  2  6  3

In [246]:
pd.DataFrame(np.random.randint(1, 10, (5, 5)), columns=['A', 'B', 'C', 'D', 'E'])

A  B  C  D  E
0  5  8  4  1  3
1  3  8  9  5  5
2  3  4  2  7  2
3  4  4  6  8  5
4  9  6  5  3  5

In [247]:
pd.DataFrame(np.random.randint(1, 10, (5, 5)), columns=['A', 'B', 'C', 'D', 'E'],
            index=range(5, 10))

A  B  C  D  E
5  1  5  5  3  6
6  7  9  1  5  1
7  4  7  3  7  8
8  8  4  8  9  9
9  1  4  6  6  8

In [248]:
students = pd.DataFrame({
    "Name": ['Ashish', 'Priya', 'Aman', 'Lakshya', 'Heta', 'Hanzal', 'Anjali', 'Surbhi', 'Suraj'],
    "Height": np.random.randint(140, 190, 9),
    "Weight": np.random.randint(50, 80, 9),
    "Age": np.random.randint(22, 30, 9)
})

In [249]:
students

Name  Height  Weight  Age
0   Ashish     176      52   24
1    Priya     158      77   26
2     Aman     145      69   24
3  Lakshya     186      69   27
4     Heta     154      59   28
5   Hanzal     148      53   28
6   Anjali     158      67   28
7   Surbhi     142      70   29
8    Suraj     149      63   29

In [250]:
type(students)

pandas.core.frame.DataFrame

In [252]:
type(students['Name'])

pandas.core.series.Series

In [254]:
type(students.iloc[0])

pandas.core.series.Series

In [256]:
students[2]
# default access column like this so here it is finding column with name 2

KeyError: 2

In [257]:
students['Name']

0     Ashish
1      Priya
2       Aman
3    Lakshya
4       Heta
5     Hanzal
6     Anjali
7     Surbhi
8      Suraj
Name: Name, dtype: object

In [258]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    9 non-null      object
 1   Height  9 non-null      int32 
 2   Weight  9 non-null      int32 
 3   Age     9 non-null      int32 
dtypes: int32(3), object(1)
memory usage: 308.0+ bytes


In [260]:
desc = students.describe()

In [261]:
desc

Height     Weight        Age
count    9.000000   9.000000   9.000000
mean   157.333333  64.333333  27.000000
std     14.688431   8.321658   1.936492
min    142.000000  52.000000  24.000000
25%    148.000000  59.000000  26.000000
50%    154.000000  67.000000  28.000000
75%    158.000000  69.000000  28.000000
max    186.000000  77.000000  29.000000

In [262]:
type(desc)

pandas.core.frame.DataFrame

In [264]:
desc['Height']

count      9.000000
mean     157.333333
std       14.688431
min      142.000000
25%      148.000000
50%      154.000000
75%      158.000000
max      186.000000
Name: Height, dtype: float64

In [265]:
desc['Weight']

count     9.000000
mean     64.333333
std       8.321658
min      52.000000
25%      59.000000
50%      67.000000
75%      69.000000
max      77.000000
Name: Weight, dtype: float64

In [267]:
desc['Age']

count     9.000000
mean     27.000000
std       1.936492
min      24.000000
25%      26.000000
50%      28.000000
75%      28.000000
max      29.000000
Name: Age, dtype: float64

In [269]:
students = pd.DataFrame({
    "Name": ['Ashish', 'Priya', 'Aman', 'Lakshya', 'Heta', 'Hanzal', 'Anjali', 'Surbhi', 'Suraj'],
    "Height": np.random.randint(140, 190, 9),
    "Weight": np.random.randint(50, 80, 9),
    "Age": np.random.randint(22, 30, 9),
    "Gender": pd.Categorical(['M', 'F', 'M', 'M', 'F', 'M', 'F', 'F', 'M'])
})

In [270]:
students

Name  Height  Weight  Age Gender
0   Ashish     171      63   29      M
1    Priya     140      55   29      F
2     Aman     171      61   26      M
3  Lakshya     180      66   22      M
4     Heta     186      65   25      F
5   Hanzal     181      56   24      M
6   Anjali     152      56   25      F
7   Surbhi     181      53   25      F
8    Suraj     165      55   27      M

In [271]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   Name    9 non-null      object  
 1   Height  9 non-null      int32   
 2   Weight  9 non-null      int32   
 3   Age     9 non-null      int32   
 4   Gender  9 non-null      category
dtypes: category(1), int32(3), object(1)
memory usage: 441.0+ bytes


In [278]:
students.iloc[8, 4] = "Male"

ValueError: Cannot setitem on a Categorical with a new category, set the categories first

In [280]:
students.shape

(9, 5)

In [281]:
students.size

45