In [2]:
import numpy as np
from random import randint

In [ ]:
[[name, maths, science, eng]]

In [3]:
l1 = [i for i in range(10000)]
l2 = [i for i in range(10000)]
l = [l1[i] + l2[i] for i in range(10000)]

In [4]:
l[:10]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
len(l)

10000

In [7]:
%%timeit

l1 = list(range(10000))
l2 = list(range(10000))
l = [l1[i] + l2[i] for i in range(10000)]

3.24 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%%timeit

a1 = np.arange(10000)
a2 = np.arange(10000)
a = a1 + a2

52.1 µs ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [10]:
print(dir(np.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uni

In [11]:
print(dir(np.math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


### Array 

    Dimensions 
        1. 1D
        2. 2D
        3. 3D
        etc 

#### 1D Array

In [12]:
l = [1, 2, 3, 4, 5, 6, 7]
arr = np.array(l)

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.dtype  # data type

dtype('int32')

In [16]:
arr.ndim # dimension

1

In [17]:
arr.shape  # number of elements in dim 

(7,)

In [18]:
arr.size  # total number of elements

7

In [20]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
arr.mean()

4.0

In [23]:
arr.std()

2.0

In [24]:
arr.var()

4.0

In [25]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [26]:
np.median(arr)

4.0

In [27]:
from statistics import mode

In [28]:
mode(arr)

1

In [29]:
arr

array([1, 2, 3, 4, 5, 6, 7])

    indexing 

In [30]:
arr = np.array([randint(1, 10) for i in range(10)])

In [31]:
arr

array([ 7, 10,  1,  5,  7,  7, 10,  3,  8,  9])

In [32]:
arr.dtype

dtype('int32')

In [34]:
np.array([1, 2, 3, 'hello', 'bye', 12.345])

array(['1', '2', '3', 'hello', 'bye', '12.345'], dtype='<U11')

In [35]:
np.array(['1', '2', 'hello', 'simran', 'string'])

array(['1', '2', 'hello', 'simran', 'string'], dtype='<U6')

In [38]:
np.array([1, 2, 3, 10.34, 56.89, 10.345])

array([ 1.   ,  2.   ,  3.   , 10.34 , 56.89 , 10.345])

In [39]:
np.array([1, 2, 3, 10.34, 56.89, 10.345]).dtype

dtype('float64')

In [40]:
a = list('python')
print(a)

['p', 'y', 't', 'h', 'o', 'n']


In [41]:
np.array('python')

array('python', dtype='<U6')

In [42]:
np.array((1, 2, 3, 4))

array([1, 2, 3, 4])

In [ ]:
[], (), {}, []

In [43]:
d = {'name': 'simran', 'course': 'python'}
np.array(d)

array({'name': 'simran', 'course': 'python'}, dtype=object)

In [44]:
list(d)

['name', 'course']

In [45]:
a

['p', 'y', 't', 'h', 'o', 'n']

In [47]:
arr[0]

7

In [48]:
arr

array([ 7, 10,  1,  5,  7,  7, 10,  3,  8,  9])

In [49]:
arr[-1]

9

In [51]:
arr[1] = 20  # mutable

In [52]:
arr

array([ 7, 20,  1,  5,  7,  7, 10,  3,  8,  9])

In [53]:
arr[-2]

8

In [54]:
arr[-3]

3

In [55]:
arr[::-1]

array([ 9,  8,  3, 10,  7,  7,  5,  1, 20,  7])

In [57]:
arr

array([ 7, 20,  1,  5,  7,  7, 10,  3,  8,  9])

In [58]:
arr[-10:-5:-1]

array([], dtype=int32)

In [60]:
l[-7:-5:-1]

[]

In [63]:
arr[-10:-5]

array([ 7, 20,  1,  5,  7])

In [65]:
arr

array([ 7, 20,  1,  5,  7,  7, 10,  3,  8,  9])

In [64]:
np.quantile(arr, [0.25, 0.5, 0.75])

array([5.5 , 7.  , 8.75])

#### 2D Array

    Collection of 1D Array
    [
        [1, 2, 3],
        [4, 5, 6],
        [9, 10, 12]
    ]
    
    rows and columns --> shape --> n*m --> n --> no of rows, m --> no of columns
        3*3 
        3 --> rows
        3 --> columns
        
        3*4
        3 --> rows
        4 --> columns

In [66]:
### Create 2d list with list comprehension 

In [67]:
l = []
for i in range(3):
    a = []
    for j in range(4):
        a.append(j)
    l.append(a)
print(l)

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]


In [68]:
l

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]

In [72]:
l = [[i for i in range(4)] for i in range(3)]

In [73]:
arr2d = np.array(l)

In [76]:
arr2d

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [75]:
print("\n Dimension is : ", arr2d.ndim)
print("\n Shape is : ", arr2d.shape)
print("\n Size is : ", arr2d.size)
print("\n Data Type is : ", arr2d.dtype)


 Dimension is :  2

 Shape is :  (3, 4)

 Size is :  12

 Data Type is :  int32


In [77]:
arr2d.mean()

1.5

In [81]:
arr2d

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [80]:
sum(arr2d)

array([0, 3, 6, 9])

In [82]:
sum(sum(arr2d))/12

1.5

In [84]:
arr2d.std()

1.118033988749895

In [85]:
arr2d.sum()

18

In [86]:
arr2d.var()

1.25

In [89]:
a = np.array([[1, 2], [3, 4, 5], [10, 12, 13, 14]])

<ipython-input-89-a6aa0326533d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array([[1, 2], [3, 4, 5], [10, 12, 13, 14]])


In [90]:
a.ndim

1

In [92]:
a[0]

[1, 2]

In [93]:
a[1]

[3, 4, 5]

In [94]:
a[2]

[10, 12, 13, 14]

In [95]:
a.shape

(3,)

In [96]:
a

array([list([1, 2]), list([3, 4, 5]), list([10, 12, 13, 14])],
      dtype=object)

In [97]:
a.size

3