In [1]:
import numpy as np

In [7]:
def matrix(n, m):
    l = [[int(input(f"\n [{row}][{col}] : ")) for col in range(m)] for row in range(n)]
    return l

        l1 = [
                [1, 2, 3],
                [4, 5, 6]
             ]
             
        l2 = [
                [3, 4, 5],
                [6, 7, 8]
             ]

In [8]:
n, m = int(input("\n Rows : ")), int(input("\n Columns : "))
l1 = matrix(n, m)
l2 = matrix(n, m)
add = []
for row in range(n):
    a = []
    for col in range(m):  
        a.append(l1[row][col] + l2[row][col])
    add.append(a)
print("\n Addition : ", add)
        
# row --> 0, col --> 0 , l1[0][0] + l2[0][0]
# row --> 0, col --> 1, l1[0][1] + l2[0][1]
# row --> 0, col --> 2 , l1[0][2] + l2[0][2] 


 Rows : 2

 Columns : 3

 [0][0] : 1

 [0][1] : 2

 [0][2] : 3

 [1][0] : 4

 [1][1] : 5

 [1][2] : 6

 [0][0] : 3

 [0][1] : 4

 [0][2] : 5

 [1][0] : 2

 [1][1] : 3

 [1][2] : 4

 Addition :  [[4, 6, 8], [6, 8, 10]]


In [9]:
l1

[[1, 2, 3], [4, 5, 6]]

In [10]:
l2

[[3, 4, 5], [2, 3, 4]]

In [11]:
n, m = int(input("\n Rows : ")), int(input("\n Columns : "))
l1 = matrix(n, m)
l2 = matrix(n, m)
add = [[l1[row][col]+l2[row][col] for col in range(m)] for row in range(n)]
print("\n Addition : ", add)
        
# row --> 0, col --> 0 , l1[0][0] + l2[0][0]
# row --> 0, col --> 1, l1[0][1] + l2[0][1]
# row --> 0, col --> 2 , l1[0][2] + l2[0][2] 


 Rows : 2

 Columns : 3

 [0][0] : 3

 [0][1] : 4

 [0][2] : 5

 [1][0] : 6

 [1][1] : 7

 [1][2] : 8

 [0][0] : 1

 [0][1] : 2

 [0][2] : 3

 [1][0] : 5

 [1][1] : 6

 [1][2] : 7

 Addition :  [[4, 6, 8], [11, 13, 15]]


In [12]:
l2

[[1, 2, 3], [5, 6, 7]]

In [14]:
arr = matrix(3, 4)


 [0][0] : 3

 [0][1] : 4

 [0][2] : 5

 [0][3] : 1

 [1][0] : 2

 [1][1] : 3

 [1][2] : 6

 [1][3] : 7

 [2][0] : 8

 [2][1] : 3

 [2][2] : 2

 [2][3] : 1


In [15]:
arr

[[3, 4, 5, 1], [2, 3, 6, 7], [8, 3, 2, 1]]

In [17]:
arr = np.array(arr)

In [18]:
arr

array([[3, 4, 5, 1],
       [2, 3, 6, 7],
       [8, 3, 2, 1]])

In [19]:
arr[0]

array([3, 4, 5, 1])

In [20]:
arr[1]

array([2, 3, 6, 7])

In [21]:
arr[2]

array([8, 3, 2, 1])

In [23]:
arr[1][3] = 17

In [24]:
arr

array([[ 3,  4,  5,  1],
       [ 2,  3,  6, 17],
       [ 8,  3,  2,  1]])

In [25]:
arr[::-1]  # row inverse

array([[ 8,  3,  2,  1],
       [ 2,  3,  6, 17],
       [ 3,  4,  5,  1]])

In [27]:
arr[::-1][::-1]

array([[ 3,  4,  5,  1],
       [ 2,  3,  6, 17],
       [ 8,  3,  2,  1]])

In [29]:
arr[1, 3]  # [row_indexing/slicing, col_indexing/slicing]

17

In [31]:
arr[0, 2]

5

In [32]:
arr[::-1, ::-1]

array([[ 1,  2,  3,  8],
       [17,  6,  3,  2],
       [ 1,  5,  4,  3]])

In [34]:
arr[::-1]

array([[ 8,  3,  2,  1],
       [ 2,  3,  6, 17],
       [ 3,  4,  5,  1]])

In [35]:
arr

array([[ 3,  4,  5,  1],
       [ 2,  3,  6, 17],
       [ 8,  3,  2,  1]])

In [36]:
arr[::2, ::2]

array([[3, 5],
       [8, 2]])

In [37]:
arr[:2, :]

array([[ 3,  4,  5,  1],
       [ 2,  3,  6, 17]])

In [38]:
arr[:, 2]

array([5, 6, 2])

In [39]:
arr[:, ::2]

array([[3, 5],
       [2, 6],
       [8, 2]])

In [40]:
np.random.randint(1, 10, 50)

array([8, 2, 3, 2, 1, 7, 4, 6, 8, 2, 1, 4, 3, 1, 2, 4, 4, 1, 7, 9, 8, 1,
       8, 9, 3, 6, 7, 2, 5, 8, 2, 7, 3, 4, 1, 1, 5, 4, 5, 9, 5, 5, 9, 4,
       3, 6, 1, 5, 7, 7])

In [42]:
arr2d = np.random.randint(1, 10, (10, 5))

In [43]:
arr2d

array([[9, 2, 6, 1, 5],
       [2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7],
       [9, 4, 3, 1, 9],
       [7, 1, 7, 5, 2],
       [5, 7, 6, 4, 6],
       [7, 2, 4, 2, 4],
       [4, 9, 4, 9, 7],
       [5, 9, 4, 8, 7],
       [1, 9, 7, 7, 4]])

    [[3, 8, 1],
     [4, 6, 7],
     [8, 4, 9]
    ]

In [45]:
arr2d[2:5:8 ,1:3:-1]

array([], shape=(1, 0), dtype=int32)

In [46]:
arr2d[3:10:2, 1:4:-1]

array([], shape=(4, 0), dtype=int32)

In [47]:
arr2d[2:9:3, 3:0:-1]

array([[3, 8, 1],
       [4, 6, 7],
       [8, 4, 9]])

In [48]:
arr2d[2::3, -2:-5:-1]

array([[3, 8, 1],
       [4, 6, 7],
       [8, 4, 9]])

In [44]:
arr2d[2:8:2, ::-1]

array([[7, 3, 8, 1, 8],
       [2, 5, 7, 1, 7],
       [4, 2, 4, 2, 7]])

In [49]:
arr2d.mean()

5.24

In [50]:
arr

array([[ 3,  4,  5,  1],
       [ 2,  3,  6, 17],
       [ 8,  3,  2,  1]])

In [51]:
arr.mean(axis=0) # column wise

array([4.33333333, 3.33333333, 4.33333333, 6.33333333])

In [53]:
(3+2+8)/3

4.333333333333333

In [57]:
(5+6+2)/3

4.333333333333333

In [58]:
19/3

6.333333333333333

In [59]:
arr.mean(axis=1)  # row wise

array([3.25, 7.  , 3.5 ])

In [60]:
sum([ 3,  4,  5,  1])/4

3.25

In [61]:
arr.sum()

55

In [62]:
arr

array([[ 3,  4,  5,  1],
       [ 2,  3,  6, 17],
       [ 8,  3,  2,  1]])

In [63]:
arr.sum(axis=1)

array([13, 28, 14])

In [64]:
sum([ 3,  4,  5,  1])

13

In [66]:
arr.sum(axis=0)

array([13, 10, 13, 19])

### 3D

    collection of 2D array
    
    [
        [
            [1, 2],
            [3, 4]
        ],
        
        [
            [1, 2],
            [3, 4]
        ],
    ]

### Create a function which will create 3D list using list comprehension
    Also subtract 3D list using List Comprehension

In [67]:
arr3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [1, 2],
        [3, 4]
    ]
])

In [68]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [69]:
print("\n Dim : ", arr3d.ndim)
print("\n Shape : ", arr3d.shape)  # (no_of_2d array, rows, columns)
print("\n Size : ", arr3d.size)
print("\n Data Type : ", arr3d.dtype)


 Dim :  3

 Shape :  (2, 2, 2)

 Size :  8

 Data Type :  int32


In [70]:
a = np.array([
    [
        [1, 2],
        [3, 4],
        [13, 14]
    ],
    [
        [1, 2],
        [3, 4]
    ]
])

<ipython-input-70-11bb111a8a86>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array([


In [71]:
a.ndim

1

In [72]:
a

array([list([[1, 2], [3, 4], [13, 14]]), list([[1, 2], [3, 4]])],
      dtype=object)

In [73]:
a.shape

(2,)

In [74]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [75]:
arr3d.mean()

2.5

In [76]:
arr3d.sum()

20

In [77]:
arr3d.var()

1.25

In [78]:
arr3d.std()

1.118033988749895

In [79]:
arr3d.tobytes()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00'

In [81]:
arr2d.tobytes()

b'\t\x00\x00\x00\x02\x00\x00\x00\x06\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x03\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x05\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x04\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x05\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x07\x00\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00'

In [86]:
arr2d

array([[9, 2, 6, 1, 5],
       [2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7],
       [9, 4, 3, 1, 9],
       [7, 1, 7, 5, 2],
       [5, 7, 6, 4, 6],
       [7, 2, 4, 2, 4],
       [4, 9, 4, 9, 7],
       [5, 9, 4, 8, 7],
       [1, 9, 7, 7, 4]])

In [83]:
arr2d.tofile('one.txt')

In [84]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 766E-A7C0

 Directory of C:\Users\Simran Grover\Grras Solution Pvt. Ltd\DataScience_11 00AM - Live Class ??\datascience_notes\Analysis\Numpy

26-08-2021  12:36    <DIR>          .
26-08-2021  12:36    <DIR>          ..
26-08-2021  11:35    <DIR>          .ipynb_checkpoints
24-08-2021  12:05             9,629 1. Numpy.ipynb
25-08-2021  12:49            38,424 2. Numpy.ipynb
26-08-2021  12:35            24,159 3. Numpy.ipynb
26-08-2021  12:36               200 one.txt
               4 File(s)         72,412 bytes
               3 Dir(s)  191,825,608,704 bytes free


In [85]:
with open("one.txt") as fp:
    print(fp.read())

								


In [87]:
b = arr2d.tobytes()

In [88]:
b

b'\t\x00\x00\x00\x02\x00\x00\x00\x06\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x03\x00\x00\x00\x07\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x05\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x04\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x05\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x07\x00\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00'

In [90]:
arr2d

array([[9, 2, 6, 1, 5],
       [2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7],
       [9, 4, 3, 1, 9],
       [7, 1, 7, 5, 2],
       [5, 7, 6, 4, 6],
       [7, 2, 4, 2, 4],
       [4, 9, 4, 9, 7],
       [5, 9, 4, 8, 7],
       [1, 9, 7, 7, 4]])

In [92]:
arr2d.dtype

dtype('int32')

In [94]:
b = np.frombuffer(b)
b.dtype = np.int32

In [96]:
b.reshape(10, 5)  # reshape is used to change shape of arr

array([[9, 2, 6, 1, 5],
       [2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7],
       [9, 4, 3, 1, 9],
       [7, 1, 7, 5, 2],
       [5, 7, 6, 4, 6],
       [7, 2, 4, 2, 4],
       [4, 9, 4, 9, 7],
       [5, 9, 4, 8, 7],
       [1, 9, 7, 7, 4]])

In [99]:
b.reshape(5, 10)

array([[9, 2, 6, 1, 5, 2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7, 9, 4, 3, 1, 9],
       [7, 1, 7, 5, 2, 5, 7, 6, 4, 6],
       [7, 2, 4, 2, 4, 4, 9, 4, 9, 7],
       [5, 9, 4, 8, 7, 1, 9, 7, 7, 4]])

In [101]:
arr2d.reshape(50)

array([9, 2, 6, 1, 5, 2, 1, 4, 7, 9, 8, 1, 8, 3, 7, 9, 4, 3, 1, 9, 7, 1,
       7, 5, 2, 5, 7, 6, 4, 6, 7, 2, 4, 2, 4, 4, 9, 4, 9, 7, 5, 9, 4, 8,
       7, 1, 9, 7, 7, 4])

In [103]:
arr2d.reshape(25, 2)

array([[9, 2],
       [6, 1],
       [5, 2],
       [1, 4],
       [7, 9],
       [8, 1],
       [8, 3],
       [7, 9],
       [4, 3],
       [1, 9],
       [7, 1],
       [7, 5],
       [2, 5],
       [7, 6],
       [4, 6],
       [7, 2],
       [4, 2],
       [4, 4],
       [9, 4],
       [9, 7],
       [5, 9],
       [4, 8],
       [7, 1],
       [9, 7],
       [7, 4]])

In [105]:
np.fromfile("one.txt").dtype 

dtype('float64')

In [106]:
f = np.fromfile("one.txt")
f.dtype = np.int32

In [108]:
f

array([9, 2, 6, 1, 5, 2, 1, 4, 7, 9, 8, 1, 8, 3, 7, 9, 4, 3, 1, 9, 7, 1,
       7, 5, 2, 5, 7, 6, 4, 6, 7, 2, 4, 2, 4, 4, 9, 4, 9, 7, 5, 9, 4, 8,
       7, 1, 9, 7, 7, 4])

In [110]:
arr.tostring()

<ipython-input-110-0bbd0773f9e8>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr.tostring()


b'\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x06\x00\x00\x00\x11\x00\x00\x00\x08\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00'

In [111]:
arr.tolist()

[[3, 4, 5, 1], [2, 3, 6, 17], [8, 3, 2, 1]]

In [113]:
arr3d.shape

(2, 2, 2)

In [115]:
arr3d[0]

array([[1, 2],
       [3, 4]])

In [116]:
arr3d[1]

array([[1, 2],
       [3, 4]])

In [117]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [120]:
arr3d[0][0][0]

1

In [122]:
arr3d[1][0][0] = 10

In [123]:
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[10,  2],
        [ 3,  4]]])

In [125]:
arr3d[::-1][::-1]

array([[[ 1,  2],
        [ 3,  4]],

       [[10,  2],
        [ 3,  4]]])

In [126]:
arr3d[::-1, ::-1]  # [2d_array, row, col]

array([[[ 3,  4],
        [10,  2]],

       [[ 3,  4],
        [ 1,  2]]])

In [127]:
arr3d[::-1, ::-1, ::-1]

array([[[ 4,  3],
        [ 2, 10]],

       [[ 4,  3],
        [ 2,  1]]])

In [128]:
arr2d

array([[9, 2, 6, 1, 5],
       [2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7],
       [9, 4, 3, 1, 9],
       [7, 1, 7, 5, 2],
       [5, 7, 6, 4, 6],
       [7, 2, 4, 2, 4],
       [4, 9, 4, 9, 7],
       [5, 9, 4, 8, 7],
       [1, 9, 7, 7, 4]])

    [
        [2, 1, 4, 7, 9],
        [8, 1, 8, 3, 7],
        [7, 1, 7, 5, 2],
        [7, 2, 4, 2, 4],
        [4, 9, 4, 9, 7]
     ]

In [134]:
arr2d[[1, 2, 4, 6, 7]]

array([[2, 1, 4, 7, 9],
       [8, 1, 8, 3, 7],
       [7, 1, 7, 5, 2],
       [7, 2, 4, 2, 4],
       [4, 9, 4, 9, 7]])

In [135]:
arr2d[[1, 2, 4, 6, 7], ::-1]

array([[9, 7, 4, 1, 2],
       [7, 3, 8, 1, 8],
       [2, 5, 7, 1, 7],
       [4, 2, 4, 2, 7],
       [7, 9, 4, 9, 4]])

In [137]:
arr2d[[1, 2, 4, 6, 7], 3:]

array([[7, 9],
       [3, 7],
       [5, 2],
       [2, 4],
       [9, 7]])

In [138]:
arr2d[:, [1, 2, 4]]

array([[2, 6, 5],
       [1, 4, 9],
       [1, 8, 7],
       [4, 3, 9],
       [1, 7, 2],
       [7, 6, 6],
       [2, 4, 4],
       [9, 4, 7],
       [9, 4, 7],
       [9, 7, 4]])

In [139]:
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[10,  2],
        [ 3,  4]]])

In [140]:
arr3d[:, 1, :]

array([[3, 4],
       [3, 4]])

In [142]:
arr3d[:, 1, 1]

array([4, 4])

In [145]:
b = arr2d.reshape(2, 5, 5)

In [147]:
b[:, [0, 3, 4], :]

array([[[9, 2, 6, 1, 5],
        [9, 4, 3, 1, 9],
        [7, 1, 7, 5, 2]],

       [[5, 7, 6, 4, 6],
        [5, 9, 4, 8, 7],
        [1, 9, 7, 7, 4]]])