In [1]:
import numpy as np

In [2]:
def d3_array(d, n, m):
    final = []
    for i in range(d):
        a = []
        for row in range(n):
            b = []
            for col in range(m):
                b.append(int(input()))
            a.append(b)
        final.append(a)
    return final

d3_array(2, 2, 2)

3
4
5
1
2
6
7
8


[[[3, 4], [5, 1]], [[2, 6], [7, 8]]]

In [3]:
def d3_array(d, n, m):
    final = [[[int(input()) for i in range(m)] for j in range(n)] for k in range(d)]
    return final 

d3_array(2, 2, 2)

3
4
5
1
2
6
7
8


[[[3, 4], [5, 1]], [[2, 6], [7, 8]]]

In [4]:
np.random.randint(1, 10, (2, 5, 5))

array([[[5, 2, 1, 6, 1],
        [2, 2, 2, 4, 4],
        [2, 9, 1, 1, 9],
        [8, 9, 3, 4, 1],
        [4, 2, 3, 1, 1]],

       [[8, 2, 4, 2, 1],
        [6, 9, 9, 5, 3],
        [6, 8, 4, 2, 1],
        [4, 6, 9, 8, 3],
        [2, 8, 6, 1, 9]]])

In [26]:
arr3 = np.random.randint(1, 10, 75).reshape(3, 5, 5)

In [27]:
arr3

array([[[2, 5, 4, 2, 8],
        [8, 3, 8, 7, 2],
        [3, 1, 2, 7, 4],
        [9, 4, 5, 9, 8],
        [6, 5, 3, 7, 6]],

       [[8, 4, 5, 4, 4],
        [5, 3, 6, 9, 4],
        [5, 6, 3, 5, 2],
        [5, 2, 9, 2, 1],
        [7, 6, 5, 8, 9]],

       [[7, 3, 8, 2, 7],
        [9, 7, 3, 2, 4],
        [3, 8, 4, 1, 6],
        [8, 7, 2, 5, 4],
        [3, 6, 9, 2, 7]]])

In [22]:
arr3.dtype

dtype('int32')

In [24]:
arr3.dtype = np.float16

In [25]:
round(arr3[1][1][3])

0

In [28]:
arr3

array([[[2, 5, 4, 2, 8],
        [8, 3, 8, 7, 2],
        [3, 1, 2, 7, 4],
        [9, 4, 5, 9, 8],
        [6, 5, 3, 7, 6]],

       [[8, 4, 5, 4, 4],
        [5, 3, 6, 9, 4],
        [5, 6, 3, 5, 2],
        [5, 2, 9, 2, 1],
        [7, 6, 5, 8, 9]],

       [[7, 3, 8, 2, 7],
        [9, 7, 3, 2, 4],
        [3, 8, 4, 1, 6],
        [8, 7, 2, 5, 4],
        [3, 6, 9, 2, 7]]])

    [
      [[8, 3],
      [2, 1],
      [5, 4],
      [3, 5]],
      
      [[6, 3],
      [3, 6],
      [9, 2],
      [5, 6]]
    ]
      

In [29]:
arr3[:,1:, 2:0:-1]

array([[[8, 3],
        [2, 1],
        [5, 4],
        [3, 5]],

       [[6, 3],
        [3, 6],
        [9, 2],
        [5, 6]],

       [[3, 7],
        [4, 8],
        [2, 7],
        [9, 6]]])

In [31]:
arr3[:,1:,-3:-5:-1]

array([[[8, 3],
        [2, 1],
        [5, 4],
        [3, 5]],

       [[6, 3],
        [3, 6],
        [9, 2],
        [5, 6]],

       [[3, 7],
        [4, 8],
        [2, 7],
        [9, 6]]])

In [33]:
arr = np.random.randint(1, 10, (2, 2, 2))

In [35]:
arr.mean()

5.0

In [36]:
arr.sum()

40

In [38]:
arr

array([[[9, 4],
        [9, 4]],

       [[3, 1],
        [8, 2]]])

In [37]:
arr.mean(axis=0)

array([[6. , 2.5],
       [8.5, 3. ]])

In [39]:
arr.mean(axis=1) # col

array([[9. , 4. ],
       [5.5, 1.5]])

In [40]:
arr.mean(axis=2) # row

array([[6.5, 6.5],
       [2. , 5. ]])

In [41]:
arr.sum(axis=1)

array([[18,  8],
       [11,  3]])

In [42]:
arr.sum(axis=2)

array([[13, 13],
       [ 4, 10]])

### Operations 

In [43]:
ages = np.random.randint(5, 15, 10)

In [44]:
ages

array([ 7, 10,  5,  7,  7, 12,  6, 12, 14,  8])

In [45]:
ages>45

array([False, False, False, False, False, False, False, False, False,
       False])

In [47]:
l = [1, 2, 3, 4]

In [48]:
l > 4

TypeError: '>' not supported between instances of 'list' and 'int'

In [51]:
ages<8

array([ True, False,  True,  True,  True, False,  True, False, False,
       False])

In [53]:
ages==7

array([ True, False, False,  True,  True, False, False, False, False,
       False])

In [55]:
l[True]

2

In [56]:
l

[1, 2, 3, 4]

In [57]:
l[False]

1

In [58]:
l[True, True]

TypeError: list indices must be integers or slices, not tuple

In [62]:
ages[ages>10]

array([12, 12, 14])

In [65]:
ages[[True, False, True, False, True, True, False, False, True, False]]

array([ 7,  5,  7, 12, 14])

In [66]:
ages[[True, False, True, False, True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 5

In [69]:
[i for i in ages if i>10]

[12, 12, 14]

In [70]:
ages

array([ 7, 10,  5,  7,  7, 12,  6, 12, 14,  8])

#### Number of students with age greater than 10

In [74]:
len(ages[ages>10])

3

In [76]:
(ages>10).sum()

3

In [80]:
ages = np.random.randint(5, 16, 30)

In [83]:
(ages>10).sum()

8

In [84]:
10<ages<=13

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
(ages>10) and (ages<=13) # or
# ages>10
#[True, False, False] and [True, False, True]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [88]:
(ages>10)

array([ True, False,  True, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False, False,  True, False,  True, False,  True,
       False, False, False])

In [87]:
any((ages>10))

True

In [89]:
(ages<=13)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True])

In [86]:
any((ages>10)) and any((ages<=13)) 

True

In [91]:
(ages>10) & (ages<=13)

array([ True, False,  True, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False])

In [92]:
ages[(ages>10) & (ages<=13)]

array([11, 13, 11, 12, 12, 11])

In [93]:
((ages>10) & (ages<=13)).sum()

6

In [94]:
any([True, False, True, True]) # if there is any True value it will return True

True

In [95]:
any([False, False, False]) # if there is any True value it will return True

False

In [96]:
all([True, False, True, True]) 

False

In [97]:
all([True, True, True, True]) 

True

In [99]:
any([0, 1, (), []])

True

In [102]:
ages[(ages>13) | (ages<10)]

array([ 5,  5,  9,  5,  9,  6,  9,  6,  8,  6, 15,  7,  6,  5,  6,  7,  5,
        5, 14,  5,  8,  7])

In [103]:
maths = np.random.randint(50, 100, 10)
sci = np.random.randint(50, 100, 10)
eng = np.random.randint(50, 100, 10)
names = np.array(list("ABCDEFGHIJ"))

In [104]:
len(maths) == len(sci) == len(eng) == len(names)

True

#### Names of students having eng marks greater than 70

In [106]:
eng[eng>70]

array([89, 94, 99, 83])

In [108]:
names[eng>70]

array(['B', 'E', 'G', 'H'], dtype='<U1')

In [113]:
(eng == eng.max()).sum()

1

In [114]:
(maths == maths.max()).sum()

2

In [115]:
maths.max()

96

In [116]:
(sci == sci.max()).sum()

1

In [117]:
sci.max()

95

#### Is there any of studens/students having maximum marks in 3 of the subject
##### if yes? Then what is its name?

In [118]:
names[eng==eng.max()]

array(['G'], dtype='<U1')

In [120]:
names[(eng==eng.max()) & (maths == maths.max()) & (sci == sci.max())]

array([], dtype='<U1')

In [121]:
arr = (eng==eng.max()) & (maths == maths.max()) & (sci == sci.max())
if any(arr):
    print(names[arr])
else:
    print("\n There is no such student with maximum marks in each subject...")


 There is no such student with maximum marks in each subject...


In [122]:
maths[(eng==eng.max())]

array([94])

In [123]:
sci[(eng==eng.max())]

array([85])

In [2]:
m=np.random.randint(40,100,20)
a=np.random.randint(40,100,20)
b=np.random.randint(40,100,20)


In [17]:
a= np.random.randint(-4,5,9)
b= np.random.randint(-4,5,9)

In [20]:
a=a.reshape(3,3)
b=b.reshape(3,3)

In [22]:
print(a)
print(b)

[[ 3  1  3]
 [-4  2  4]
 [-1  0 -1]]
[[-2 -4 -2]
 [ 1 -3 -1]
 [-2  2  4]]


In [24]:
res=[]
for i in range(len(a)):
    sum=0
    for j in range(len(b)):
        sum=a[i][j]*b[j][i]+sum
    
    res.append(sum)
    

In [25]:
res

[-11, 18, -2]