In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 10, 10)

In [4]:
1/arr

array([0.5       , 0.11111111, 0.5       , 1.        , 0.11111111,
       0.25      , 0.2       , 0.11111111, 0.14285714, 0.5       ])

In [5]:
arr

array([2, 9, 2, 1, 9, 4, 5, 9, 7, 2])

In [6]:
1/0

ZeroDivisionError: division by zero

In [7]:
arr/0

<ipython-input-7-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [9]:
a = np.zeros(10)

In [10]:
1/a

<ipython-input-10-f2f92b2a85cc>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

        [
           [35 30 35 30 35],
           [35 30 35 30 35],
           [35 30 35 30 35],
           [35 30 35 30 35],
           [35 30 35 30 35],
        ]

In [19]:
np.zeros((5, 5))+6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [28]:
a = (np.ones((5, 5), dtype=np.int32)*5) * (np.zeros((5, 5), dtype=np.int32)+6)

In [29]:
a[:, ::2] += 5

In [30]:
a

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35]])

In [31]:
arr

array([2, 9, 2, 1, 9, 4, 5, 9, 7, 2])

In [32]:
np.append(arr, 10)

array([ 2,  9,  2,  1,  9,  4,  5,  9,  7,  2, 10])

In [33]:
np.append(arr, [10, 20, 30])

array([ 2,  9,  2,  1,  9,  4,  5,  9,  7,  2, 10, 20, 30])

In [34]:
np.append(arr, [[10, 20, 30]])

array([ 2,  9,  2,  1,  9,  4,  5,  9,  7,  2, 10, 20, 30])

In [35]:
a

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35]])

In [36]:
np.append(a, 10)

array([35, 30, 35, 30, 35, 35, 30, 35, 30, 35, 35, 30, 35, 30, 35, 35, 30,
       35, 30, 35, 35, 30, 35, 30, 35, 10])

In [38]:
np.append(a, [10, 20, 30, 40, 50])

array([35, 30, 35, 30, 35, 35, 30, 35, 30, 35, 35, 30, 35, 30, 35, 35, 30,
       35, 30, 35, 35, 30, 35, 30, 35, 10, 20, 30, 40, 50])

In [39]:
np.append(a, [[10, 20, 30, 40, 50]])

array([35, 30, 35, 30, 35, 35, 30, 35, 30, 35, 35, 30, 35, 30, 35, 35, 30,
       35, 30, 35, 35, 30, 35, 30, 35, 10, 20, 30, 40, 50])

In [41]:
np.append(a, [[10, 20, 30, 40, 50]], axis=0)  # axis=0 --> rows append

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [10, 20, 30, 40, 50]])

In [44]:
np.append(a, [[10, 10], [20, 20], [30, 35], [40, 44], [50, 21]], axis=1)  # axis=1 --> column append

array([[35, 30, 35, 30, 35, 10, 10],
       [35, 30, 35, 30, 35, 20, 20],
       [35, 30, 35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35, 40, 44],
       [35, 30, 35, 30, 35, 50, 21]])

In [45]:
a

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35]])

In [47]:
arr = np.append(arr, [10, 20, 30])

In [48]:
arr

array([ 2,  9,  2,  1,  9,  4,  5,  9,  7,  2, 10, 20, 30])

In [53]:
np.concatenate([arr, [10]])

array([ 2,  9,  2,  1,  9,  4,  5,  9,  7,  2, 10, 20, 30, 10])

In [55]:
np.concatenate([arr, [10, 20, 3, 3, 5, 6]])

array([ 2,  9,  2,  1,  9,  4,  5,  9,  7,  2, 10, 20, 30, 10, 20,  3,  3,
        5,  6])

In [56]:
a1 = np.random.randint(1, 10, 10)
a2 = np.random.randint(10, 20, 10)
a3 = np.random.randint(15, 21, 10)

In [57]:
a1

array([2, 9, 1, 3, 1, 6, 8, 1, 2, 5])

In [58]:
a2

array([12, 10, 17, 19, 15, 14, 18, 13, 12, 15])

In [59]:
a3

array([16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [60]:
np.concatenate([a1, a2])

array([ 2,  9,  1,  3,  1,  6,  8,  1,  2,  5, 12, 10, 17, 19, 15, 14, 18,
       13, 12, 15])

In [61]:
np.append(a1, a2)

array([ 2,  9,  1,  3,  1,  6,  8,  1,  2,  5, 12, 10, 17, 19, 15, 14, 18,
       13, 12, 15])

In [63]:
np.concatenate([a, a])

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35]])

In [69]:
np.concatenate([a, [[10, 12, 13, 14, 15]]])

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [10, 12, 13, 14, 15]])

In [71]:
np.concatenate([a, [[10], [12], [13], [14], [15]]], axis=1)

array([[35, 30, 35, 30, 35, 10],
       [35, 30, 35, 30, 35, 12],
       [35, 30, 35, 30, 35, 13],
       [35, 30, 35, 30, 35, 14],
       [35, 30, 35, 30, 35, 15]])

In [66]:
np.append(a, a, axis=0)

array([[35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35],
       [35, 30, 35, 30, 35]])

In [72]:
a1

array([2, 9, 1, 3, 1, 6, 8, 1, 2, 5])

In [73]:
a2

array([12, 10, 17, 19, 15, 14, 18, 13, 12, 15])

In [75]:
a3

array([16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [78]:
np.append(a1, a2, a3)

TypeError: only integer scalar arrays can be converted to a scalar index

In [80]:
ages = np.concatenate([a1, a2, a3])

In [81]:
ages

array([ 2,  9,  1,  3,  1,  6,  8,  1,  2,  5, 12, 10, 17, 19, 15, 14, 18,
       13, 12, 15, 16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [83]:
ages.max()

20

In [84]:
ages[29]

20

In [82]:
ages.argmax()
# return the index of maximum element

29

In [85]:
ages.argmin()

2

In [90]:
l = list(ages)
l.index(max(l))

29

In [91]:
def argmin(arr):
    """Return the index of minimum element in the array"""
    index = 0
    min_ = arr[0]
    for i in range(1, len(arr)):
        if min_ > arr[i]:
            min_ = arr[i]
            index = i
    return index

In [92]:
argmin(ages)

2

In [93]:
ages

array([ 2,  9,  1,  3,  1,  6,  8,  1,  2,  5, 12, 10, 17, 19, 15, 14, 18,
       13, 12, 15, 16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [96]:
ages.argsort()

array([ 2,  4,  7,  0,  8,  3,  9,  5,  6,  1, 11, 10, 18, 17, 15, 19, 14,
       28, 20, 21, 22, 23, 26, 12, 16, 13, 24, 25, 27, 29], dtype=int64)

In [95]:
ages[ages.argsort()]

array([ 1,  1,  1,  2,  2,  3,  5,  6,  8,  9, 10, 12, 12, 13, 14, 15, 15,
       16, 16, 16, 16, 16, 16, 17, 18, 19, 19, 19, 19, 20])

In [101]:
ages

array([ 2,  9,  1,  3,  1,  6,  8,  1,  2,  5, 12, 10, 17, 19, 15, 14, 18,
       13, 12, 15, 16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [102]:
ages[12]

17

In [99]:
np.where(ages>14)

(array([12, 13, 14, 16, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       dtype=int64),)

In [103]:
ages[np.where(ages>14)]

array([17, 19, 15, 18, 15, 16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [104]:
np.where(ages>14, ages, ages**2)

array([  4,  81,   1,   9,   1,  36,  64,   1,   4,  25, 144, 100,  17,
        19,  15, 196,  18, 169, 144,  15,  16,  16,  16,  16,  19,  19,
        16,  19,  16,  20])

In [100]:
ages>14

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [105]:
np.where(ages>14, ages, ages**2)3

array([  4,  81,   1,   9,   1,  36,  64,   1,   4,  25, 144, 100,  17,
        19,  15, 196,  18, 169, 144,  15,  16,  16,  16,  16,  19,  19,
        16,  19,  16,  20])

In [106]:
ages

array([ 2,  9,  1,  3,  1,  6,  8,  1,  2,  5, 12, 10, 17, 19, 15, 14, 18,
       13, 12, 15, 16, 16, 16, 16, 19, 19, 16, 19, 16, 20])

In [107]:
ages**2

array([  4,  81,   1,   9,   1,  36,  64,   1,   4,  25, 144, 100, 289,
       361, 225, 196, 324, 169, 144, 225, 256, 256, 256, 256, 361, 361,
       256, 361, 256, 400], dtype=int32)

In [109]:
np.where(ages>14, ages**2, ages)
# condition, arr1, arr2
# the condition at which the elements are true it will return from arr1 else from arr2

array([  2,   9,   1,   3,   1,   6,   8,   1,   2,   5,  12,  10, 289,
       361, 225,  14, 324,  13,  12, 225, 256, 256, 256, 256, 361, 361,
       256, 361, 256, 400])

In [110]:
np.where(ages>14, True, False)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [112]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [113]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [119]:
np.arange(20, 100, 2).reshape(5, 8)

array([[20, 22, 24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78, 80, 82],
       [84, 86, 88, 90, 92, 94, 96, 98]])

In [120]:
np.arange(4, 1, -1)

array([4, 3, 2])

In [121]:
np.linspace(0, 1, 8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [122]:
0.14285714 - 0

0.14285714

In [123]:
0.28571429 - 0.14285714

0.14285715

In [124]:
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [125]:
np.linspace(1, 2, 50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])