In [1]:
import numpy as np

In [2]:
from random import randint

In [11]:
randint(1, 10) # start = 1, stop = 10

7

In [8]:
help(randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [18]:
np.random.randint(1, 11, 20)

array([ 3,  3, 10,  7,  6,  8,  4,  3,  4,  2,  6,  8,  6,  1,  6,  6,  5,
        8,  4,  6])

In [17]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [3]:
arr = np.random.randint(0, 31, 30)

In [4]:
arr

array([12, 21, 27, 19, 10,  7,  4, 24, 17,  9,  2, 18, 27,  6, 21, 22,  1,
       15, 30,  3, 28, 12, 20,  7, 12, 21, 19, 27,  1, 28])

In [22]:
np.floor(3.2)

3.0

In [23]:
np.ceil(3.2)

4.0

In [24]:
arr = np.random.randint(0, 31, 30)

In [30]:
arr

array([22, 24,  0, 25,  6,  0,  4, 21,  0,  9,  0, 23, 15, 30, 30,  8,  3,
       12, 18, 12,  8,  0,  3, 20, 23,  6,  5, 30, 11, 12])

In [33]:
def freq(arr, ll, ul):
    count = 0
    for val in range(ll, ul):
        num = 0
        for i in arr:
            if i == val:
                num += 1 # num = 1 + 1 = 2, 2 + 1 = 3
        count += num # count = 0, count = 0 + 5 = 5
        #print(val, num)
    return count
freq(arr, 0, 5) # ll = 0, ul = 5, 
# val = 0, num = 0, 

8

In [40]:
N = len(arr)
k = round(1 + 3.322*np.log10(N))
range_ = max(arr) - min(arr)
size = int(np.ceil(range_/k))
print("|\tIntervals\t|\tFrequency\t|")
print("_"*50)
for i in range(min(arr), max(arr)+1, size):
    print(f"|\t{i} - {i+size}\t\t|\t{freq(arr, i, i+size)}\t\t|")
    print("_"*50)

|	Intervals	|	Frequency	|
__________________________________________________
|	0 - 5		|	8		|
__________________________________________________
|	5 - 10		|	6		|
__________________________________________________
|	10 - 15		|	4		|
__________________________________________________
|	15 - 20		|	2		|
__________________________________________________
|	20 - 25		|	6		|
__________________________________________________
|	25 - 30		|	1		|
__________________________________________________
|	30 - 35		|	3		|
__________________________________________________


In [48]:
N = len(arr)
k = round(1 + 3.322*np.log10(N))
range_ = max(arr) - min(arr)
size = int(np.ceil(range_/k))
print("|\tIntervals\t|\tFrequency\t|\tLess Than CF\t|\tMore Than CF\t|")
print("_"*100)
lcf = 0
mcf = len(arr)
for i in range(min(arr), max(arr)+1, size):
    c = freq(arr, i, i+size)
    lcf += c
    print(f"|\t{i} - {i+size}\t\t|\t{c}\t\t|\t\t{lcf}\t|\t\t{mcf}\t|")
    mcf -= c
    print("_"*100)

|	Intervals	|	Frequency	|	Less Than CF	|	More Than CF	|
____________________________________________________________________________________________________
|	0 - 5		|	8		|		8	|		30	|
____________________________________________________________________________________________________
|	5 - 10		|	6		|		14	|		22	|
____________________________________________________________________________________________________
|	10 - 15		|	4		|		18	|		16	|
____________________________________________________________________________________________________
|	15 - 20		|	2		|		20	|		12	|
____________________________________________________________________________________________________
|	20 - 25		|	6		|		26	|		10	|
____________________________________________________________________________________________________
|	25 - 30		|	1		|		27	|		4	|
____________________________________________________________________________________________________
|	30 - 35		|	3		|		30	|		3	|
_________________________________

### More Questions

    1. Find Cumulative Percentage Frequency Table
    2. Calculate mean of grouped frequency distribution table
    3. Calculate weighted Arithemetic mean

        5     2
        6     3
        7     10
        4     5

In [14]:
def freq(arr, ll, ul):
    count = 0
    for val in range(ll, ul):
        num = 0
        for i in arr:
            if i == val:
                num += 1 # num = 1 + 1 = 2, 2 + 1 = 3
        count += num # count = 0, count = 0 + 5 = 5
        #print(val, num)
    return count
def main():
    N = len(arr)
    k = round(1 + 3.322*np.log10(N))
    range_ = max(arr) - min(arr)
    size = int(np.ceil(range_/k))
    print("|\tIntervals\t|\tFrequency\t|\tMid\t|\td\t|\tfd\t|")
    print("_"*100)
    mid = []
    f = []
    for i in range(min(arr), max(arr)+1, size):
        ll = i
        ul = i + size
        m = (ll + ul)//2
        mid.append(m)
        f.append(freq(arr, i, i+size))
    pos = round(len(mid)/2)
    A = mid[pos-1]
    d = [(mid[i] - A)/size for i in range(len(mid))]
    fd = [f[i]*d[i] for i in range(len(f))]
    c = 0
    for i in range(min(arr), max(arr)+1, size):
        print(f"|\t{i} - {i+size}\t\t|\t{f[c]}\t\t|\t{mid[c]}\t|\t{d[c]}\t|\t{fd[c]}\t|")
        print("_"*100)
        c += 1
main()

|	Intervals	|	Frequency	|	Mid	|	d	|	fd	|
____________________________________________________________________________________________________
|	1 - 6		|	5		|	3	|	-2.0	|	-10.0	|
____________________________________________________________________________________________________
|	6 - 11		|	5		|	8	|	-1.0	|	-5.0	|
____________________________________________________________________________________________________
|	11 - 16		|	4		|	13	|	0.0	|	0.0	|
____________________________________________________________________________________________________
|	16 - 21		|	5		|	18	|	1.0	|	5.0	|
____________________________________________________________________________________________________
|	21 - 26		|	5		|	23	|	2.0	|	10.0	|
____________________________________________________________________________________________________
|	26 - 31		|	6		|	28	|	3.0	|	18.0	|
____________________________________________________________________________________________________


In [11]:
6/2

3.0

### Quartiles

    values --> 10 20 30 40 50
    
    Q2 --> Median of your data = 30
    Q1 --> median of smaller values than the Q2 
            median of 10 and 20 will be Q1
    Q3 --> median of greater values than the Q2 
            median of 40 and 50 will be Q3

#### Measures of Spread

    1. Deviation
    2. Std Deviation
    3. Variance
    4. Range

$$ deviation = \frac{\sum\limits_{i=0}^N |(\bar x - x_i)|} {N} $$

$$ variance = \frac{\sum\limits_{i=0}^N (\bar x - x_i)^2} {N} $$

$$ std = \sqrt{\frac{\sum\limits_{i=0}^N (\bar x - x_i)^2} {N}} $$